stages:
  - publish
  - deploy

build-docker-env:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/php:8.1" "."
    - docker push "$CI_REGISTRY_IMAGE/php:8.1"
  when:
    manual

deploy:
  stage: deploy
  variables:
    DEPLOY_PATH: "/var/www/flaminfo_fr/app-cow"

  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - echo "Deploy path $DEPLOY_PATH"
    - ssh-add <(echo "$ID_RSA" | base64 -d)
    - umask 0027
    - git archive HEAD | ssh $SERVER_USER@$SERVER_IP "umask 0027; tar x --no-overwrite-dir --owner=paul --group=www-data -mC $DEPLOY_PATH/"

  environment:
    name: production
    url: https://app-cow.flaminfo.fr
  only:
    - master




