stages:
  - test
  - deploy

deploy:
  stage: deploy
  variables:
    DEPLOY_PATH: /var/www/flaminfo_fr/app-cow
    SERVER: paul@flaminfo.fr
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy path $DEPLOY_PATH"
    - ssh-add <(echo "$ID_RSA" | base64 -d)
    - umask 0027
    - git archive HEAD | ssh $SERVER "umask 0027; tar x --no-overwrite-dir --owner=paul --group=www-data -mC $DEPLOY_PATH/"
    - ssh $SERVER "chgrp -R www-data $DEPLOY_PATH/"
    - ssh $SERVER "chmod -R 750 $DEPLOY_PATH/"
    - ssh $SERVER "chmod -R g+s $DEPLOY_PATH/"
    - ssh $SERVER "rm -r $DEPLOY_PATH/uploads"
    - ssh $SERVER "mkdir $DEPLOY_PATH/uploads"
    - ssh $SERVER "chmod g+sw $DEPLOY_PATH/uploads"
  environment:
    name: production
    url: https://app-cow.flaminfo.fr
  only:
    - master

deploy_review:
  stage: deploy
  variables:
    DEPLOY_PATH: /var/www/flaminfo_fr/app-cow/website_review/$CI_ENVIRONMENT_SLUG
    SERVER: paul@flaminfo.fr
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy path $DEPLOY_PATH"
    - ssh-add <(echo "$DEPLOY_KEY" | base64 -d)
    - ssh $SERVER "rm -rf $DEPLOY_PATH/"
    - umask 0027
    - ssh $SERVER "mkdir -p $DEPLOY_PATH/"
    - git archive HEAD | ssh $SERVER "umask 0027; tar x --no-overwrite-dir --owner=paul --group=www-data -mC $DEPLOY_PATH/"
    - ssh $SERVER "mkdir $DEPLOY_PATH/uploads"
    - ssh $SERVER "cp $DEPLOY_PATH/../../uploads/* $DEPLOY_PATH/uploads"
    - ssh $SERVER "chmod g+sw $DEPLOY_PATH/uploads"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    deployment_tier: development
    url: https://test.app-cow.flaminfo.fr/$CI_ENVIRONMENT_SLUG
    on_stop: stop_review
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_ID

stop_review:
  stage: deploy
  variables:
    SERVER: paul@flaminfo.fr
    DEPLOY_PATH: /var/www/flaminfo_fr/app-cow/website_review/$CI_ENVIRONMENT_SLUG
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy path $DEPLOY_PATH"
    - ssh-add <(echo "$DEPLOY_KEY" | base64 -d)
    - ssh $SERVER "rm -rf $DEPLOY_PATH/"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual